#!/usr/bin/env bash
# Install and configure a load balancer
sudo apt-get update -y
sudo apt-get install haproxy -y

echo -e "\nfrontend Server\n\tbind *:80\n\tmode http\n\tdefault_backend nodes\n\nbackend nodes\n\tbalance roundrobin\n\tserver 45304-web-01 44.210.15.198 check\n\tserver 45304-web-02 44.210.15.198 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
