#!/usr/bin/env bash
#I not love you

sudo touch /var/run/holbertonscript.pid
sudo chmod 777 /var/run/holbertonscript.pid
var=$(pgrep -f 100-process_and_pid_file)
echo "$var" >> /var/run/holbertonscript.pid

sigterm()
{
    echo "I hate the kill command"
    sudo rm /var/run/holbertonscript.pid
    exit 0
}
sigint()
{
    echo "Y U no love me?!"
}

trap "sigterm" SIGTERM
trap "sigterm" SIGQUIT
trap "sigint" SIGINT
while ((1)); do
    echo "To infinity and beyond"
    sleep 2
done
